apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: homepage-ingress
spec:
  rules:
  - host: homepage.cluster.domain
    http:
      paths:
      - backend:
          serviceName: homepage
          servicePort: 80
        path: /